# Turn off compliance along these dimensions.
# Order matters: [translation-x, translation-y, translation-z, rotation-x, rotation-y, rotation-z]
# Give 'true' to enable compliance in the direction, 'false' to not be compliant
# E.g. [true, false, false, true, false, false] would enable compliance in the EEF x translation and roll
bool[] dimensions_to_ignore
---
bool success
